name: morning
on:
  schedule:
    - cron: '00 23 * * *'  # 23:00 UTC (北京时间 7:00 AM)
  workflow_dispatch:

jobs:
  send_message:
    runs-on: windows-latest
    name: send morning to your girlfriend

    steps:
    - name: Checkout code
      uses: actions/checkout@v3
      with:
        ref: master

    - name: Check system time
      run: Get-Date  # 获取系统时间 (PowerShell 命令)
      shell: pwsh

    - name: Set time zone to CST (China Standard Time)
      run: |
        tzutil /s "China Standard Time"  # 设置时区为中国标准时间（CST）
      shell: pwsh

    - name: Install dependencies
      run: |
        choco install python --version 3.9.0 -y  # 安装指定版本的 Python
        python -m pip install --upgrade pip  # 更新 pip
        pip install -r ./requirements.txt  # 安装项目依赖
      shell: pwsh

    - name: Send message
      run: python ./main.py  # 执行 Python 脚本
      shell: pwsh

    env:
      APP_ID: ${{ secrets.APP_ID }}
      APP_SECRET: ${{ secrets.APP_SECRET }}
      TEMPLATE_ID: ${{ secrets.TEMPLATE_ID }}
      USER_ID: ${{ secrets.USER_ID }}
      START_DATE: ${{ secrets.START_DATE }}
      BIRTHDAY: ${{ secrets.BIRTHDAY }}
      CITY: ${{ secrets.CITY }}
      PERIOD_DATE: ${{ secrets.PERIOD_DATE }}
      WEATHER_KEY: ${{ secrets.WEATHER_KEY }}
      XM_USER_ID: ${{ secrets.XM_USER_ID }}
